# Generated by Django 3.0.3 on 2020-03-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('stu_father_name', models.CharField(max_length=200)),
                ('stu_mother_name', models.CharField(max_length=200)),
                ('stu_father_occupation', models.CharField(max_length=100)),
                ('stu_mother_occupation', models.CharField(max_length=100)),
                ('stu_father_mobilenumber', models.PositiveIntegerField(max_length=10)),
                ('stu_mother_mobilenumber', models.PositiveIntegerField(max_length=10)),
                ('stu_class', models.CharField(max_length=150)),
                ('stu_batch', models.CharField(max_length=150)),
                ('stu_gender', models.CharField(max_length=120)),
            ],
        ),
    ]
