# Generated by Django 3.0.3 on 2020-03-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20200304_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_father_mobilenumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_mother_mobilenumber',
            field=models.BigIntegerField(),
        ),
    ]
